server:
  port: 8080

spring:
  datasource:
    master:
      url: jdbc:mysql://127.0.0.1:3306/test?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
    slave1:
      url: jdbc:mysql://127.0.0.1:13306/test?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
      username: root   # 只读账户
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
    slave2:
      url: jdbc:mysql://127.0.0.1:23306/test?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
      username: root   # 只读账户
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.entity